# Generated by Django 5.2.15 on 2026-06-20 05:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialRefSys',
            fields=[
                ('srid', models.IntegerField(primary_key=True, serialize=False)),
                ('auth_name', models.CharField(blank=True, max_length=256, null=True)),
                ('auth_srid', models.IntegerField(blank=True, null=True)),
                ('srtext', models.CharField(blank=True, max_length=2048, null=True)),
                ('proj4text', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'spatial_ref_sys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('rut', models.CharField(max_length=15, unique=True)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.TextField()),
                ('password_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
            options={
                'db_table': 'products',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DriverPositions',
            fields=[
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.users')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'driver_positions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cylinders',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=50)),
                ('type', models.TextField()),
                ('status', models.TextField()),
                ('driver_name', models.CharField(blank=True, max_length=150, null=True)),
                ('capture_url', models.TextField(blank=True, null=True)),
                ('needs_manual_validation', models.BooleanField()),
                ('registered_at', models.DateTimeField()),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.users')),
            ],
            options={
                'db_table': 'cylinders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('client_name', models.CharField(max_length=150)),
                ('client_phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('payment_method', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.TextField()),
                ('security_token', models.CharField(max_length=4)),
                ('driver_name', models.CharField(blank=True, max_length=150, null=True)),
                ('driver_plate', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.users')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders_driver_set', to='core.users')),
                ('product', models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.DO_NOTHING, to='core.products')),
            ],
            options={
                'db_table': 'orders',
                'managed': True,
            },
        ),
    ]
