# Generated by Django 5.2.15 on 2026-06-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_driverpositions_updated_at_auto_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password_hash',
            field=models.CharField(max_length=255),
        ),
    ]
